---
title: "Lab 1"
author: "Ksenia Gordeeva"
date: "4/9/2022"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(rio)
library(here)
library(dplyr)
```

### Data Structures


```{r}
set.seed(123) # Set random number generation

m <- lm(mpg ~ hp + cyl + drat, mtcars)

l <- list(a = list(m = matrix(1:12, ncol = 3),
              	   v = 1:7),
          b = data.frame(student = 1:15,
                         score = rnorm(15, 100, 10))) 
```

1. From the model results:
	* Extract the qr tolerance (`tol`).
```{r}
#str(m)
#Extract the qr tolerance
m[["qr"]][["tol"]]

#Alternatively: 
#m$qr$tol
```
	* Extract the term labels from the model.
```{r}
#Term Labels
term_attributes <- attr(m$model, "terms")
attr(term_attributes, "term.labels")

#Alternatively:
#attr(m[["terms"]], "term.labels")
```

2. From the list
	* Use at least two different methods to extract `m`.
```{r}
#1
l[["a"]][["m"]]

#2
l$a$m
```
	* Extract the third column of `m`. Maintain the dimensions (matrix structure).
```{r}
l[["a"]][["m"]][ ,3, drop = FALSE]
```
	* Extract the score for student 7.
```{r}
l$b[7, ]

#ALternatively: 
#l[["b"]][7, ]
```

